#!/usr/bin/env php
<?php

if (file_exists(__DIR__.'/vendor/autoload.php')) {
    require __DIR__.'/vendor/autoload.php';
} else {
    require __DIR__.'/../../autoload.php';
}

if (! defined('BASE_PATH')) {
    define('BASE_PATH', __DIR__);
}

/**
 * Laravel Zero - An elegant starting point for your next Laravel Console Application
 *
 * @package  Laravel Zero
 * @author   Nuno Maduro <enunomaduro@gmail.com>
 */

(new App\Console\Application)->run();
