#!/usr/bin/env php
<?php

require __DIR__.'/bootstrap/autoload.php';

/**
 * Laravel Zero - An elegant starting point for your next Laravel Console Application
 *
 * @package  Laravel Zero
 * @author   Nuno Maduro <enunomaduro@gmail.com>
 */

(new App\Console\Application)->run();
